INSERT INTO filetypes (filename) VALUES ('JavaScript');
INSERT INTO filetypes (filename) VALUES ('Python');
INSERT INTO filetypes (filename) VALUES ('Java');
INSERT INTO filetypes (filename) VALUES ('C++');
INSERT INTO filetypes (filename) VALUES ('C');
INSERT INTO filetypes (filename) VALUES ('HTML');
INSERT INTO filetypes (filename) VALUES ('CSS');
INSERT INTO filetypes (filename) VALUES ('PHP');
INSERT INTO filetypes (filename) VALUES ('Ruby');
INSERT INTO filetypes (filename) VALUES ('Swift');
INSERT INTO filetypes (filename) VALUES ('TypeScript');
INSERT INTO filetypes (filename) VALUES ('C#');
INSERT INTO filetypes (filename) VALUES ('Go');
INSERT INTO filetypes (filename) VALUES ('R');
INSERT INTO filetypes (filename) VALUES ('Perl');
INSERT INTO filetypes (filename) VALUES ('SQL');
INSERT INTO filetypes (filename) VALUES ('Shell Script');
INSERT INTO filetypes (filename) VALUES ('Lua');
INSERT INTO filetypes (filename) VALUES ('React JSX');
INSERT INTO filetypes (filename) VALUES ('React TypeScript');
INSERT INTO filetypes (filename) VALUES ('Vue.js');
INSERT INTO filetypes (filename) VALUES ('Sass');
INSERT INTO filetypes (filename) VALUES ('SCSS');
INSERT INTO filetypes (filename) VALUES ('Less');
INSERT INTO filetypes (filename) VALUES ('JSON');
INSERT INTO filetypes (filename) VALUES ('YAML');
INSERT INTO filetypes (filename) VALUES ('XML');
INSERT INTO filetypes (filename) VALUES ('SVG');
INSERT INTO filetypes (filename) VALUES ('Markdown');
INSERT INTO filetypes (filename) VALUES ('YAML');
